name: Build

on:
  push:
    branches: [ main ]
    tags: ['*']
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ~1.21

      - name: Setup protoc
        uses: arduino/setup-protoc@v2
        with:
          version: 25.1

      - name: Install protoc-gen-twirp-java
        run: go install github.com/ngyewch/protoc-gen-twirp-java@v0.1.0

      - name: Generate Twirp sources
        run: |
          mkdir -p ${OUTPUT_DIR}
          protoc --proto_path=${PB_DIR} \
            --twirp-java_out=${OUTPUT_DIR} \
            --twirp-java_opt=gen-helidon-client=true \
            --twirp-java_opt=gen-helidon-server=true \
            service.proto
        env:
          PB_DIR: src/main/proto
          OUTPUT_DIR: build/generated/source/protoc-gen-twirp-java/main/java

      - name: Build Java project
        run: ./gradlew build
